"""Change table name from Users to User

Revision ID: 24f6cc786490
Revises: 616def8f097d
Create Date: 2022-02-23 19:38:28.053188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24f6cc786490'
down_revision = '616def8f097d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.Column('confirm_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('confirm', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('confirm_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.drop_table('user')
    # ### end Alembic commands ###
