"""about author Added

Revision ID: 3295322e5673
Revises: ca1fbba7cc9a
Create Date: 2022-03-28 10:01:44.757278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3295322e5673'
down_revision = 'ca1fbba7cc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_author')
    # ### end Alembic commands ###
