"""added name, username fields

Revision ID: 616def8f097d
Revises: 
Create Date: 2022-02-22 13:11:51.987933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616def8f097d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
